# Documentation on how to configure the bundle can be found at: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"
    filter_sets:
        thumbail:
            format: jpeg
            quality: 80
            filters:
                thumbnail: { size: [360, 230], mode: outbound }
        card:
            quality: 80
            filters:
                thumbnail: { size: [700, 500], mode: outbound }
    # app/config/config.yml

#liip_imagine:

    # configure resolvers
#    resolvers:

        # setup the default resolver
#        default:

            # use the default web path
#            web_path: ~

    # your filter sets are defined here
#    filter_sets:

        # use the default cache configuration
#        cache: ~
